title: Abhaya Libre Font by mooniak - අභය අකුරු රටාව
desc: the unicode compliant libre release of Pushpananda Ekanayakess FM Abhaya font. A mooniak release.
baseurl:  /abhaya-libre-font
font_name: AbhayaLibre
family_name: AbhayaLibre
thumb_url:
glyphs: අ ඉ ඊ උ එ ඔ ක ඛ ග ඝ ච ට ඩ න ප ව හ
string_sinhala: නවවන අටක ඉනට එවන එන චවන අගවන අපව කඩන කනකට ගහක උනට අඩපන එට ගහ අනන ඔප නවවන අගවන ඉඩකඩ අහක එක කනකට පටවන අක වගව අහගන අග අඩපන වඩවන ගහක අට අටවන නව කහ උගහට නටවන පවට අඩපන කවට කටවහ එ ච අගවන නගන පනවන පටක වගව කටට කටහඩ ඊ එකග පටවන කටට අඩපන ගන අ වට නටවන ඊටට අහන ඉඩකඩ චනට ඔපවන එකට අගවන චන අටවක අඩක උප අගවන වඩවන අඩපන කටවහ නවක අක වඩ පනවන පවකට කව කනකට ඝන වනට අගවන උපන හඩ පහට නටන ඔපවන චන අටක උඩ ඉව කවන පටවන එකට අඩ නවවන අහගන නවන අහගන පනවන පටවන එකග උපන චන වඩවන පවකට පවකට වඩ පටවන අගවන ඔපවන ටක හඩ ගහන කන ඉනට ක අටවක උගහට කන උහන කටවහ කවට පනවන ග ඉඩක නටවන එකක කහන ඉඩක එට උපන උගහට
string_latin: novas snappiness idea viands edison avion iodopsins ass nose peon spininess eve sod dividends possisdendi denda assidaean pep anapes aped dispossessed vendean pinons despises is diseasedness desidiose seas a pain sod do peep anne openendedness novas spoon evase do nee spondean en spondean saanen on seasides andia ion dissava poseidon is as indivision nonpossessive avidnesses an asap vinea pinnas pips dispassion iso aid save sane div en possessedness ped



safe: false
lsi: false
pygments: true


# About/contact
author:
  name:              Pathum Egodawatta
  url:               https://twitter.com/pathumego
  email:             pathum@mooniak.com

# Custom vars
version:             0.0.1

exclude:
  - README.md
